### ISSUE TITLE
Feedback for “Front Matter Reference”

### ISSUE THREAD

**Issue by pieterdnz** [bigcommerce/dev-docs#1952]
Hi there is small "bug" in the documentation on de blog section

https://developer.bigcommerce.com/stencil-docs/reference-docs/front-matter-reference#blog-attributes

If u want to limit de summery it states that u should do:

```
blog:
    recent_posts:
        limit: {{theme_settings.detail_blog_posts_count}}
    summary: 1000
```

but that does not work

it should be

```
blog:
    recent_posts:
        limit: {{theme_settings.detail_blog_posts_count}}
        summary: 1000

```
